<a href="https://colab.research.google.com/github/alstj003/2024-intro-DA-code/blob/main/w04_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##numpy.vstack()

In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [5]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [6]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [7]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [9]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [10]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

##numpy.hstack()

In [11]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [14]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [15]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [16]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

##numpy.column_stack()

In [18]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [20]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [21]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [22]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [23]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [24]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [25]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [26]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [27]:
np.column_stack == np.hstack

False

##numpy.row_stack()

In [28]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [30]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [31]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [32]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [33]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [34]:
np.row_stack == np.vstack

True

##numpy.concatenate()

In [35]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [37]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [40]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [3]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [5]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [6]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [7]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [8]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [9]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [10]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [11]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

##numpy.stack()

In [12]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [13]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [14]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [19]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [20]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [21]:
ax0.shape

(3, 2, 3)

In [22]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [24]:
ax1.shape

(2, 3, 3)

In [25]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [26]:
ax2.shape

(2, 3, 3)

In [27]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [29]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [30]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [31]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [32]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [33]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [34]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

##column_stack()과 hstack()

In [35]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [37]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [38]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [39]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [41]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

##row_stack()과 vstack()

In [42]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [44]:
np.row_stack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [45]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

##np.c_[]와 np.column_stack()

In [46]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [47]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [50]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [51]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [52]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

##np.r_[] 개요

In [53]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [54]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [55]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [56]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [58]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [59]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [60]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

##np.r_['i, j, k', a, b]

In [61]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
np.r_[a, a, a]  #concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [63]:
np.r_['0', a, a]  #concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [64]:
np.r_['-1', a, a]  #concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [65]:
np.r_['1', a, a]  #concatenate along last axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [66]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]  #concatenate along first axis, dim>=2

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]  #concatenate along first axis, dim>=3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [68]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [69]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [70]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [71]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

##여러 1차원 배열을 수평 방향으로 합치는 방법

In [72]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [73]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [74]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [75]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

##여러 1차원 배열을 수직 방향으로 합치는 방법

In [76]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [77]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

##여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [80]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [81]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [86]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#CODE THE END